// Example code

#pragma once

#include "ST-LIB.hpp"

// AUTOGENERATED CODE - DO NOT MODIFY BY HAND

class DataPackets {
   private:
    constexpr static size_t N_PACKETS{1};

   public:
    static Packet *battery_1;

    static std::array<Packet *, N_PACKETS> packets;

    DataPackets(float &soc1, double &cell1, float &cell2, float &cell3) {
        battery_1 = new StackPacket(910, &soc1, &cell1, &cell2, &cell3);

        packets[0] = battery_1;
    }
};

class OBCCU {
    DataPackets data;
    OBCCU() { data = DataPackets(soc1, cell1, cell2, cell3); }

    void init() {
        Time::register_low_precision_alarm(
            100, [&]() { Socket.send(data.battery_1); })
    }
}