/*
* AUTOGENERATED FILE 
* DO NOT MODIFY MANUALLY!!!
*/
extern "C"{
    const char DESCRIPTION[255]  __attribute__((section(".metadata_pool")))= 
        "****************"  // placeholder for beggining
        "20250911T161045"   // DateTime using ISO-8601 format
        " "                 // alignment
        "1af648a0"          // STLIB commit
        "--------"          // ADJ commit
        "f845aa56"          // Board commit
        // the '=' is used for unparsing
        ;
}