/*
* AUTOGENERATED FILE 
* DO NOT MODIFY MANUALLY!!!
*/
extern "C"{
    const char DESCRIPTION[255]  __attribute__((section(".metadata_pool")))= 
        "****************"  // placeholder for beggining
        "***************"   // DateTime using ISO-8601 format
        " "                 // alignment
        "--------"          // STLIB commit
        "--------"          // ADJ commit
        "--------"          // Board commit
        // the '=' is used for unparsing
        ;
}