#pragma once
#include "ST-LIB.hpp"
using namespace std::chrono_literals;

// AUTOGENERATED CODE, DO NOT EDIT MANUALLY

class GeneratedStateMachine{

    public:
    
    static bool from_1_to_2();
    static bool from_1_to_2();
    static bool from_1_to_nested_1();

    static void enter_action_1();
    static void enter_action_2();
    static void enter_action_3();
    static void enter_action_4();

    static void low_precision_action();
    static void low_precision_action();

    static void mid_precision_action_to_nested_state();
    static void mid_precision_action_to_nested_state();

    static void high_precision_action_with_description();
    static void high_precision_action_with_description();

    static void exit_action_1();
    static void exit_action_2();



    enum GeneralStates {
        NAME_1,
        NAME_2,
    };

    enum Nested_sm{
        NESTED_NAME_1,
        NESTED_NAME_2,
    };

    GeneratedStateMachine(){

        StateMachine general_state_machine = StateMachine(GeneralStates::NAME_1);

        StateMachine Nested_sm = StateMachine(NESTED_NAME_1);
        general_state_machine.add_state_machine(Nested_sm,NESTED_NAME_1);
        Nested_sm.add_state(NESTED_NAME_2);
        general_state_machine.add_state(GeneralStates::NAME_2);

    
        general_state_machine.add_transition(GeneralStates::NAME_1,GeneralStates::NAME_2,from_1_to_2);
        // Transitioning from 1 to 2
        general_state_machine.add_transition(GeneralStates::NAME_1,GeneralStates::NAME_2,from_1_to_2);

    
        general_state_machine.add_enter_action(enter_action_1,GeneralStates::NAME_1);
        general_state_machine.add_enter_action(enter_action_2,GeneralStates::NAME_1);
        // Description of enter_action_3
        general_state_machine.add_enter_action(enter_action_3,GeneralStates::NAME_2);
        general_state_machine.add_enter_action(enter_action_4,GeneralStates::NAME_2);

        general_state_machine.add_low_precision_cyclic_action(low_precision_action,30ms,GeneralStates::NAME_1);
        general_state_machine.add_low_precision_cyclic_action(low_precision_action,30ms,GeneralStates::NAME_2);

        general_state_machine.add_mid_precision_cyclic_action(mid_precision_action_to_nested_state,60ms,GeneralStates::NAME_1);
        general_state_machine.add_mid_precision_cyclic_action(mid_precision_action_to_nested_state,60ms,Nested_sm::NESTED_NAME_1);

        // Cyclic action example with description
        general_state_machine.add_high_precision_cyclic_action(high_precision_action_with_description,90ms,GeneralStates::NAME_1);
        // Cyclic action example with description
        general_state_machine.add_high_precision_cyclic_action(high_precision_action_with_description,90ms,GeneralStates::NAME_2);

        general_state_machine.add_exit_action(exit_action_1,Nested_sm::NESTED_NAME_2);
        general_state_machine.add_exit_action(exit_action_2,Nested_sm::NESTED_NAME_2);


    }

    
};

