#pragma once
#include "ST-LIB.hpp"

//Data packets for {{board}} -AUTOGENERATED CODE, DO NOT MODIFY-
class DataPackets{
    {% for enum in enums %}enum class {{enum.name}}:uint8_t
    {
    {% for value in enum["values"] %}{{value}}={{loop.index0}}{%if not loop.last%},{%endif%}
    {% endfor %}};

    {%endfor %}

    private:
        constexpr static size_t size={{size}};
        uint32_t id{0};
    public:
        std::array<StackPacket*,size> packets; 
        {%for packet in packets%}StackPacket* {{packet.name}};
        {% endfor %}

        {% for socket in sockets %}{{socket.type}}* {{socket.name}} = nullptr;
        {% endfor %}
        
    DataPackets({%for value in data %}{{value.type}} &{{value.name}}{%if not loop.last%},{%endif%}{%endfor%})
{   
    {% for socket in ServerSockets%}{{socket.name}} = new ServerSocket("{{socket.board_ip}}",{{socket.port}});
    {% endfor %}
    {% for socket in DatagramSockets%}{{socket.name}} = new DatagramSocket("{{socket.board_ip}}",{{socket.port}},"{{socket.remote_ip}}",{{socket.port}});
    {% endfor %}
    {% for socket in Sockets%}{{socket.name}} = new Socket("{{socket.board_ip}}",{{socket.local_port}},"{{socket.remote_ip}}",{{socket.remote_port}});
    {% endfor %}
    {% for packet in packets %}{{packet.name}} = new StackPacket({{packet.id}}{% if packet.data%},{{packet.data}}{% endif%});
    packets[id]={{packet.name}};
    id++;

    {% endfor %}
    {%for packet in sending_packets %}Time::register_low_precision_alarm({{packet.period}},[{{packet.socket}}={{packet.socket}},{{packet.name}}={{packet.name}}](){
        {{packet.socket}}->send_packet(*{{packet.name}});
    });
    {%endfor%}


}
};