#pragma once
#include "ST-LIB.hpp"

//Order packets for {{board}} -AUTOGENERATED CODE, DO NOT MODIFY-

{%for packet in packets%}extern void {{packet.name}}_cb();
{% endfor %}
class OrderPackets{
    {% for enum in enums %}enum class {{enum.name}}:uint8_t
    {
    {% for value in enum["values"] %}{{value}}={{loop.index0}}{%if not loop.last%},{%endif%}
    {% endfor %}};

    {% endfor %}

    

    private:
        uint32_t id{0};
    public:
        {%for packet in packets%}HeapOrder* {{packet.name}};
        {% endfor %}
        
    OrderPackets({%for value in data %}{{value.type}} &{{value.name}}{%if not loop.last%},{%endif%}{%endfor%})
{

    {% for packet in packets %}{{packet.name}}=new HeapOrder({{packet.id}},&{{packet.name}}_cb{% if packet.data%},{{packet.data}}{% endif%});
    {% endfor %}
}
};